//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpertSystem.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExpertSystem.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kształt łuku zębowego.
        /// </summary>
        internal static string ArchShapeQuestion {
            get {
                return ResourceManager.GetString("ArchShapeQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Koszt dla pacjenta.
        /// </summary>
        internal static string CostQuestion {
            get {
                return ResourceManager.GetString("CostQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czy występują korony kliniczne?.
        /// </summary>
        internal static string CrownQuestion {
            get {
                return ResourceManager.GetString("CrownQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czy są warunki do implantacji?.
        /// </summary>
        internal static string ImplantationQuestion {
            get {
                return ResourceManager.GetString("ImplantationQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zalecana jest korona na implancie..
        /// </summary>
        internal static string KoronaNaImplancie {
            get {
                return ResourceManager.GetString("KoronaNaImplancie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rodzaj braków .
        /// </summary>
        internal static string LackQuestion {
            get {
                return ResourceManager.GetString("LackQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jakie jest umiejscowienie zębów?.
        /// </summary>
        internal static string LocationQuestion {
            get {
                return ResourceManager.GetString("LocationQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ilu zębów brakuje?.
        /// </summary>
        internal static string MissingTeethQuestion {
            get {
                return ResourceManager.GetString("MissingTeethQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zalecany jest most dwubrzeżny cyrkonowy..
        /// </summary>
        internal static string MostDwubrzeżnyCyrkonowy {
            get {
                return ResourceManager.GetString("MostDwubrzeżnyCyrkonowy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zalecany jest most dwubrzeżny na implantach..
        /// </summary>
        internal static string MostDwubrzeżnyImplant {
            get {
                return ResourceManager.GetString("MostDwubrzeżnyImplant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zalecany jest most dwubrzeżny metalowy..
        /// </summary>
        internal static string MostDwubrzeżnyMetalowy {
            get {
                return ResourceManager.GetString("MostDwubrzeżnyMetalowy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zalecany jest most jednobrzeżny cyrkonowy..
        /// </summary>
        internal static string MostJednobrzeznyCyrkonowy {
            get {
                return ResourceManager.GetString("MostJednobrzeznyCyrkonowy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zalecany jest most jednobrzeżny metalowy..
        /// </summary>
        internal static string MostJednobrzeznyMetalowy {
            get {
                return ResourceManager.GetString("MostJednobrzeznyMetalowy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zalecana jest proteza całkowita.
        /// </summary>
        internal static string ProtezaCalkowita {
            get {
                return ResourceManager.GetString("ProtezaCalkowita", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zalecana jest proteza całkowita na lokatorach..
        /// </summary>
        internal static string ProtezaCalkowitaLokatory {
            get {
                return ResourceManager.GetString("ProtezaCalkowitaLokatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zalecana jest proteza częściowa..
        /// </summary>
        internal static string ProtezaCzesciowa {
            get {
                return ResourceManager.GetString("ProtezaCzesciowa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zalecana jest proteza OVD (overdenture)..
        /// </summary>
        internal static string ProtezaOvd {
            get {
                return ResourceManager.GetString("ProtezaOvd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaleacana jest proteza szkieletowa..
        /// </summary>
        internal static string ProtezaSzkieletowa {
            get {
                return ResourceManager.GetString("ProtezaSzkieletowa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zalecana jest proteza szkieletowa z ryglem..
        /// </summary>
        internal static string ProtezaSzkieletowaRygiel {
            get {
                return ResourceManager.GetString("ProtezaSzkieletowaRygiel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zalecana jest proteza szkieletowa z zatrzaskami..
        /// </summary>
        internal static string ProtezaSzkieletowaZatrzaski {
            get {
                return ResourceManager.GetString("ProtezaSzkieletowaZatrzaski", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zalecana jest proteza na teleskopach..
        /// </summary>
        internal static string ProtezaTeleskopy {
            get {
                return ResourceManager.GetString("ProtezaTeleskopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czy jest zachowany korzeń?.
        /// </summary>
        internal static string RootQuestion {
            get {
                return ResourceManager.GetString("RootQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jakie obciążenie okluzyje występuje?.
        /// </summary>
        internal static string StrainQuestion {
            get {
                return ResourceManager.GetString("StrainQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Witamy w systemie doradczym pomgającym wybrać rodzaj pracy protetycznej.
        /// </summary>
        internal static string WelcomeMessage {
            get {
                return ResourceManager.GetString("WelcomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zalecana jest wizyta u specjalisty..
        /// </summary>
        internal static string WizytaUSpecjalisty {
            get {
                return ResourceManager.GetString("WizytaUSpecjalisty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zalecany jest wkład plus korona cyrkonowa..
        /// </summary>
        internal static string WkladKoronaCyrkonowa {
            get {
                return ResourceManager.GetString("WkladKoronaCyrkonowa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zalecany jest wkład plus korona metalowa..
        /// </summary>
        internal static string WkladKoronaMetalowa {
            get {
                return ResourceManager.GetString("WkladKoronaMetalowa", resourceCulture);
            }
        }
    }
}
