//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpertSystem.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExpertSystem.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jakie są dodatkowe objawy?.
        /// </summary>
        public static string AdditionalSymptomsQuestion {
            get {
                return ResourceManager.GetString("AdditionalSymptomsQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stwierdzono anginę. Należy przyjmować antybiotyk, płukać gardło i spędzić min. tydzień w łóżku..
        /// </summary>
        public static string AnginaTherapy {
            get {
                return ResourceManager.GetString("AnginaTherapy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Należy zastosować tabletki z betahistyną..
        /// </summary>
        public static string BetahistineTherapy {
            get {
                return ResourceManager.GetString("BetahistineTherapy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stwierdzono przeziębienie. Należy przyjmować witaminy, anspirynę i spędzić min. 2 dni w łóżku..
        /// </summary>
        public static string ColdTherapy {
            get {
                return ResourceManager.GetString("ColdTherapy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stwierdzono grypę. Należy przyjmować antybiotyk i spędzić min. tydzień w łóżku..
        /// </summary>
        public static string FluTherapy {
            get {
                return ResourceManager.GetString("FluTherapy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stwierdzono zatrucie pokarmowe. Należy stosować dietę i przyjmować krople żołądkowe..
        /// </summary>
        public static string FoodPoisoningTherapy {
            get {
                return ResourceManager.GetString("FoodPoisoningTherapy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jaka jest płeć pacjenta?.
        /// </summary>
        public static string GenderQuestion {
            get {
                return ResourceManager.GetString("GenderQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czy stwierdzono wysoką gorączkę?.
        /// </summary>
        public static string HighFeverQuestion {
            get {
                return ResourceManager.GetString("HighFeverQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jakie stwierdzono objawy?.
        /// </summary>
        public static string OtherSymptomsQuestion {
            get {
                return ResourceManager.GetString("OtherSymptomsQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W którym miejscu występuje ból?.
        /// </summary>
        public static string PainQuestion {
            get {
                return ResourceManager.GetString("PainQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czy dolega ból gardła?.
        /// </summary>
        public static string SoreThroatQuestion {
            get {
                return ResourceManager.GetString("SoreThroatQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zalecana jest wizyta u lekarza bariatry..
        /// </summary>
        public static string VisitToABariatrist {
            get {
                return ResourceManager.GetString("VisitToABariatrist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zalecana jest wizyta u kardiologa..
        /// </summary>
        public static string VisitToACardiologist {
            get {
                return ResourceManager.GetString("VisitToACardiologist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zalecana jest wizyta u dentysty..
        /// </summary>
        public static string VisitToADentist {
            get {
                return ResourceManager.GetString("VisitToADentist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zalecana jest wizyta u dermatologa..
        /// </summary>
        public static string VisitToADermatologist {
            get {
                return ResourceManager.GetString("VisitToADermatologist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zalecana jest wizyta u dietetyka..
        /// </summary>
        public static string VisitToADietician {
            get {
                return ResourceManager.GetString("VisitToADietician", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zalecana jest wizyta u endokrynologa..
        /// </summary>
        public static string VisitToAEndocrinologist {
            get {
                return ResourceManager.GetString("VisitToAEndocrinologist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zalecana jest wizyta u gastrologa..
        /// </summary>
        public static string VisitToAGastroenterologist {
            get {
                return ResourceManager.GetString("VisitToAGastroenterologist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zalecana jest wizyta u lekarza geriatry..
        /// </summary>
        public static string VisitToAGeriatrician {
            get {
                return ResourceManager.GetString("VisitToAGeriatrician", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zalecana jest wizyta u ginekologa..
        /// </summary>
        public static string VisitToAGynecologist {
            get {
                return ResourceManager.GetString("VisitToAGynecologist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zalecana jest wizyta u laryngologa..
        /// </summary>
        public static string VisitToALaryngologist {
            get {
                return ResourceManager.GetString("VisitToALaryngologist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zalecana jest wizyta u alergologa..
        /// </summary>
        public static string VisitToAnAllergist {
            get {
                return ResourceManager.GetString("VisitToAnAllergist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zalecana jest wizyta u nefrologa..
        /// </summary>
        public static string VisitToANephrologist {
            get {
                return ResourceManager.GetString("VisitToANephrologist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zalecana jest wizyta u neurologa..
        /// </summary>
        public static string VisitToANeurologist {
            get {
                return ResourceManager.GetString("VisitToANeurologist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zalecana jest wizyta u okulisty..
        /// </summary>
        public static string VisitToAnOphthalmologist {
            get {
                return ResourceManager.GetString("VisitToAnOphthalmologist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zalecana jest wizyta u otolaryngologa..
        /// </summary>
        public static string VisitToAnOtolaryngologist {
            get {
                return ResourceManager.GetString("VisitToAnOtolaryngologist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zalecana jest wizyta u urologa..
        /// </summary>
        public static string VisitToAnUrologist {
            get {
                return ResourceManager.GetString("VisitToAnUrologist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zalecana jest wizyta u ortopedy..
        /// </summary>
        public static string VisitToAOrthopaedist {
            get {
                return ResourceManager.GetString("VisitToAOrthopaedist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zalecana jest wizyta u psychologa..
        /// </summary>
        public static string VisitToAPsychologist {
            get {
                return ResourceManager.GetString("VisitToAPsychologist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zalecana jest wizyta u pulmonologa..
        /// </summary>
        public static string VisitToAPulmonologist {
            get {
                return ResourceManager.GetString("VisitToAPulmonologist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zalecana jest wizyta u reumatologa..
        /// </summary>
        public static string VisitToARheumatologist {
            get {
                return ResourceManager.GetString("VisitToARheumatologist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zalecana jest wizyta u specjalisty..
        /// </summary>
        public static string VisitToASpecialist {
            get {
                return ResourceManager.GetString("VisitToASpecialist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zalecana jest wizyta u trychologa..
        /// </summary>
        public static string VisitToATrichologist {
            get {
                return ResourceManager.GetString("VisitToATrichologist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaleca się przyjmować magnez, witamy oraz uprawiać sport..
        /// </summary>
        public static string VitaminAndSportTherapy {
            get {
                return ResourceManager.GetString("VitaminAndSportTherapy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Witamy w systemie eksperckim pomagającym zdiagnozować chorobę..
        /// </summary>
        public static string WelcomeMessage {
            get {
                return ResourceManager.GetString("WelcomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Co dolega pacjentowi?.
        /// </summary>
        public static string WhatAilsThePatientQuestion {
            get {
                return ResourceManager.GetString("WhatAilsThePatientQuestion", resourceCulture);
            }
        }
    }
}
