//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpertSystem.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExpertSystem.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jakie są dodatkowe objawy?.
        /// </summary>
        public static string AdditionalSymptomsQuestion {
            get {
                return ResourceManager.GetString("AdditionalSymptomsQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czy stwierdzono wysoką gorączkę?.
        /// </summary>
        public static string HighFeverQuestion {
            get {
                return ResourceManager.GetString("HighFeverQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zalecany jest most dwubrzeżny cyrkonowy..
        /// </summary>
        public static string MostDwubrzeżnyCyrkonowy {
            get {
                return ResourceManager.GetString("MostDwubrzeżnyCyrkonowy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zalecany jest most dwubrzeżny na implantach..
        /// </summary>
        public static string MostDwubrzeżnyImplant {
            get {
                return ResourceManager.GetString("MostDwubrzeżnyImplant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zalecany jest most dwubrzeżny metalowy..
        /// </summary>
        public static string MostDwubrzeżnyMetalowy {
            get {
                return ResourceManager.GetString("MostDwubrzeżnyMetalowy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zalecany jest most jednobrzeżny cyrkonowy..
        /// </summary>
        public static string MostJednobrzeznyCyrkonowy {
            get {
                return ResourceManager.GetString("MostJednobrzeznyCyrkonowy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zalecany jest most jednobrzeżny metalowy..
        /// </summary>
        public static string MostJednobrzeznyMetalowy {
            get {
                return ResourceManager.GetString("MostJednobrzeznyMetalowy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jakie stwierdzono objawy?.
        /// </summary>
        public static string OtherSymptomsQuestion {
            get {
                return ResourceManager.GetString("OtherSymptomsQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W którym miejscu występuje ból?.
        /// </summary>
        public static string PainQuestion {
            get {
                return ResourceManager.GetString("PainQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zalecana jest proteza całkowita.
        /// </summary>
        public static string ProtezaCalkowita {
            get {
                return ResourceManager.GetString("ProtezaCalkowita", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zalecana jest proteza całkowita na lokatorach..
        /// </summary>
        public static string ProtezaCalkowitaLokatory {
            get {
                return ResourceManager.GetString("ProtezaCalkowitaLokatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zalecana jest proteza częściowa..
        /// </summary>
        public static string ProtezaCzesciowa {
            get {
                return ResourceManager.GetString("ProtezaCzesciowa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zalecana jest proteza OVD (overdenture)..
        /// </summary>
        public static string ProtezaOvd {
            get {
                return ResourceManager.GetString("ProtezaOvd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaleacana jest proteza szkieletowa..
        /// </summary>
        public static string ProtezaSzkieletowa {
            get {
                return ResourceManager.GetString("ProtezaSzkieletowa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zalecana jest proteza szkieletowa z ryglem..
        /// </summary>
        public static string ProtezaSzkieletowaRygiel {
            get {
                return ResourceManager.GetString("ProtezaSzkieletowaRygiel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zalecana jest proteza szkieletowa z zatrzaskami..
        /// </summary>
        public static string ProtezaSzkieletowaZatrzaski {
            get {
                return ResourceManager.GetString("ProtezaSzkieletowaZatrzaski", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zalecana jest proteza na teleskopach..
        /// </summary>
        public static string ProtezaTeleskopy {
            get {
                return ResourceManager.GetString("ProtezaTeleskopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Witamy w systemie eksperckim pomagającym zdjagnozować chorobę..
        /// </summary>
        public static string WelcomeMessage {
            get {
                return ResourceManager.GetString("WelcomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Co dolega pacjentowi?.
        /// </summary>
        public static string WhatAilsThePatientQuestion {
            get {
                return ResourceManager.GetString("WhatAilsThePatientQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zalecana jest wizyta u specjalisty..
        /// </summary>
        public static string WizytaUSpecjalisty {
            get {
                return ResourceManager.GetString("WizytaUSpecjalisty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zalecany jest wkład plus korona cyrkonowa..
        /// </summary>
        public static string WkladKoronaCyrkonowa {
            get {
                return ResourceManager.GetString("WkladKoronaCyrkonowa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zalecany jest wkład plus korona metalowa..
        /// </summary>
        public static string WkladKoronaMetalowa {
            get {
                return ResourceManager.GetString("WkladKoronaMetalowa", resourceCulture);
            }
        }
    }
}
